version: "3"

services:

  # haproxy:
  #   image: haproxy:1.8.9-alpine
  #   command: /bin/sh -c "/usr/bin/start.sh"
  #   restart: unless-stopped
  #   container_name: haproxy
  #   depends_on:
  #     - api
  #     # - frontend
  #   volumes:
  #     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  #     - ./haproxy/start.sh:/usr/bin/start.sh:ro
  #     - ./haproxy/secrets/:/secrets
  #   ports:
  #     - "80:80" # HTTP
  #     - "443:443" # HTTPS
  #     - "9000:9000" # Stats endpoint for backend management.

  db:
    image: postgres:10.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: master
      POSTGRES_PASSWORD: password
    volumes:
      - /data/app_name/postgres/data:/var/lib/postgresql/data

  api:
    image: backend
    restart: unless-stopped
    build:
      context: ./api
      args:
        - dev=--dev
    command: /start.sh
    depends_on:
      - db
    volumes:
      - "./api:/app"
    ports:
      - "8000:8000" # HTTP
