# Generated by Django 2.0 on 2018-06-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Dairy'), (1, 'Fruit'), (2, 'Grain (cereal) foods'), (3, 'Lean meats, poultry, fish, eggs, tofu, nuts and seeds'), (4, 'Vegetables, legumes and beans')], null=True),
        ),
    ]
